stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: "s6-alpine"
  IMAGE_TAG: "latest"
  GITHUB_PROJECT: "p42/s6-alpine-docker.git"

before_script:
  - docker info

build-master:
  stage: build
  script:
    - docker build --pull -t "${IMAGE_NAME}:${IMAGE_TAG}" .
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -t "${IMAGE_NAME}:${IMAGE_TAG}" .
  except:
    - master

test-master:
  stage: test
  script:
    - docker run --rm "${IMAGE_NAME}:${IMAGE_TAG}" /ci_tests/run_tests system
  only:
    - master

test:
  stage: test
  script:
    - docker run --rm "${IMAGE_NAME}:${IMAGE_TAG}" /ci_tests/run_tests system
  except:
    - master

deploy_to_github-master:
  stage: deploy
  script:
    - git push git@github.com:${GITHUB_PROJECT} master
  only:
    - master

deploy_to_github:
  stage: deploy
  script:
    - git checkout ${CI_COMMIT_REF_NAME}
    - git push git@github.com:${GITHUB_PROJECT} ${CI_COMMIT_REF_NAME}
  except:
    - master

deploy_tags_to_github:
  stage: deploy
  script:
    - git push git@github.com:${GITHUB_PROJECT} ${CI_COMMIT_REF_NAME} --tags
  only:
    - tags
