stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: "s6-alpine"
  IMAGE_TAG: "latest"
  GITHUB_PROJECT: "p42/s6-alpine-docker.git"
  DOCKER_HUB_IMAGE: "project42/s6-alpine"

before_script:
  - docker info

build-master:
  tags:
    - docker
  stage: build
  script:
    - git checkout master
    - git pull
    - docker build --pull -t "${IMAGE_NAME}:latest" .
  only:
    - master

build:
  tags:
    - docker
  stage: build
  script:
    - git checkout ${CI_COMMIT_REF_NAME}
    - git pull
    - docker build --pull -t "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}" .
  except:
    - master

test-master:
  tags:
    - docker
  stage: test
  script:
    - docker run --rm "${IMAGE_NAME}:latest" /ci_tests/run_tests system
  only:
    - master

test:
  tags:
    - docker
  stage: test
  script:
    - docker run --rm "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}" /ci_tests/run_tests system
  except:
    - master

deploy_to_github-master:
  tags:
    - docker
    - github-key
  stage: deploy
  script:
    - git checkout master
    - git push git@github.com:${GITHUB_PROJECT} master
  only:
    - master

deploy_to_github:
  tags:
    - docker
    - github-key
  stage: deploy
  script:
    - git checkout ${CI_COMMIT_REF_NAME}
    - git push git@github.com:${GITHUB_PROJECT} ${CI_COMMIT_REF_NAME}
  except:
    - master

deploy_tags_to_github:
  tags:
    - docker
    - github-key
  stage: deploy
  script:
    - git checkout ${CI_COMMIT_REF_NAME}
    - git push git@github.com:${GITHUB_PROJECT} ${CI_COMMIT_REF_NAME} --tags
  only:
    - tags

push_to_docker_hub-master:
  tags:
    - docker
    - docker-hub
    - docker-pushrm
  stage: deploy
  script:
    - docker image tag ${IMAGE_NAME}:latest ${DOCKER_HUB_IMAGE}:latest
    - docker push ${DOCKER_HUB_IMAGE}:latest
    - git checkout ${CI_COMMIT_REF_NAME}
    - docker pushrm ${DOCKER_HUB_IMAGE}:latest
  only:
    - master

push_to_docker_hub:
  tags:
    - docker
    - docker-hub
    - docker-pushrm
  stage: deploy
  script:
    - docker image tag ${IMAGE_NAME}:${CI_COMMIT_REF_NAME} ${DOCKER_HUB_IMAGE}:${CI_COMMIT_REF_NAME}
    - docker push ${DOCKER_HUB_IMAGE}:${CI_COMMIT_REF_NAME}
    - git checkout ${CI_COMMIT_REF_NAME}
    - docker pushrm ${DOCKER_HUB_IMAGE}:${CI_COMMIT_REF_NAME}
  except:
    - master
